--- 
  - hosts: all
    connection: local
    become: yes
    become_method: sudo

    vars_files:
     - ../vars/main.yml
    
    tasks:
    - name: 
      file:
        state: directory
        path: "{{ WORKSPACE_DIR }}"
        recurse: yes
      tags:
      - createcerts

      
    - name: Create CA
      raw: "cd {{ WORKSPACE_DIR }}; cfssl print-defaults csr | cfssl gencert -initca - | cfssljson -bare nomad-ca"
      tags:
      - createcerts


    - name: Create CFSSL Json
      template:
        src: ../templates/cfssl.json.j2
        dest: "{{ WORKSPACE_DIR }}/cfssl.json"
      tags:
      - createcerts    


    - name: Create Server certs
      raw: "cd {{ WORKSPACE_DIR }}; echo '{}' | cfssl gencert -ca=nomad-ca.pem -ca-key=nomad-ca-key.pem -config=cfssl.json -hostname='server.global.nomad,localhost,127.0.0.1' - | cfssljson -bare server"
      tags:
      - createcerts 


    - name: Create Client Certs
      raw: "cd {{ WORKSPACE_DIR }}; echo '{}' | cfssl gencert -ca=nomad-ca.pem -ca-key=nomad-ca-key.pem -config=cfssl.json -hostname='client.global.nomad,localhost,127.0.0.1' - | cfssljson -bare client"
      tags:
      - createcerts


    - name: Create CLI Certs
      raw: "cd {{ WORKSPACE_DIR }}; echo '{}' | cfssl gencert -ca=nomad-ca.pem -ca-key=nomad-ca-key.pem -profile=client - | cfssljson -bare cli"
      tags:
      - createcerts



